repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.0  # Use the latest version
  hooks:
    - id: ruff
      args: [--fix]
    - id: ruff-format

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-toml
    - id: check-added-large-files
      args: ['--maxkb=500']

ci:
  autofix_commit_msg: '[pre-commit.ci] Auto fixes from pre-commit hooks'
  autoupdate_commit_msg: '[pre-commit.ci] Update pre-commit hooks' 