site_name: NCAA Basketball Analytics
site_description: Documentation for NCAA Basketball Analytics Project
site_author: NCAA Basketball Analytics Team
repo_url: https://github.com/tim-mcdonnell/ncaa-basketball-analytics
repo_name: NCAA Basketball Analytics

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]

nav:
  - Home: index.md
  - Architecture:
    - architecture/index.md
    - Project Structure: architecture/project-structure.md
    - Tech Stack: architecture/tech-stack.md
    - Configuration Management: architecture/config-management.md
    - Data Table Structures: architecture/data-table-structures.md
    - Airflow Workflows: architecture/airflow-workflows.md
    - Feature Engineering: architecture/feature-engineering.md
    - Logging Strategy: architecture/logging-strategy.md
    - Model Training: architecture/model-training.md
  - Guides:
    - guides/index.md
    - Getting Started: guides/getting-started.md
    - Adding Features: guides/adding-features.md
    - Training Models: guides/training-models.md
  - API Reference:
    - api/index.md
    - Endpoints:
      - Seasons: api/endpoints/seasons.md
      - Teams: api/endpoints/teams.md
      - Athletes: api/endpoints/athletes.md
      - Events: api/endpoints/events.md
      - Rankings: api/endpoints/rankings.md
      - Awards: api/endpoints/awards.md
    - Technical Reference:
      - Data Structures: api/reference/data-structures.md
      - Query Parameters: api/reference/query-parameters.md
      - Status Codes: api/reference/status-codes.md 