###############################################
# NCAA Basketball Analytics - Base Configuration
# Version: 1.0.0
###############################################

# Configuration version
_version: "1.0.0"

# API Configuration
api:
  host: localhost
  port: 8000
  debug: false
  timeout: 30
  rate_limit: 0
  endpoints:
    teams: /api/teams
    games: /api/games
    stats: /api/stats

# Database Configuration
db:
  path: ./data/basketball.duckdb
  read_only: false
  memory_map: true
  threads: 4
  extensions:
    - json
    - httpfs
  allow_external_access: false

# Feature Configuration
feature:
  enabled: true
  cache_results: true
  parameters:
    smoothing_factor:
      value: 0.3
      description: "Smoothing factor for EMA calculation"
      min: 0.0
      max: 1.0
    window_size:
      value: 5
      description: "Window size for rolling calculations"
      min: 1
      max: 20
  dependencies:
    - stats
    - player_data
  priority: 100

# Model Configuration
model:
  type: xgboost
  feature_set: all_features
  target: win_probability
  hyperparameters:
    learning_rate: 0.01
    max_depth: 5
    num_estimators: 100
  evaluation:
    metrics:
      - accuracy
      - f1_score
    validation_split: 0.2
    cross_validation_folds: 5
  experiment_tracking:
    enabled: true
    log_artifacts: true
  random_seed: 42

# Dashboard Configuration
dashboard:
  title: NCAA Basketball Analytics
  refresh_interval: 60
  theme:
    primary_color: "#0066cc"
    secondary_color: "#f8f9fa"
    text_color: "#212529"
    background_color: "#ffffff"
    font_family: "Arial, sans-serif"
  layout:
    sidebar_width: 250
    content_width: fluid
    charts_per_row: 2
    default_chart_height: 400
  default_view: team_overview
  available_views:
    - team_overview
    - team_comparison
    - player_stats
    - predictions
  cache_timeout: 300
  show_filters: true
  max_items_per_page: 25
